#!/usr/bin/env ruby
puts "rm -rf output/**"
`rm -rf output/**`
puts "rake guides:generate"
`bundle exec rake guides:generate`

Dir["output/*.html"].each do |path|
  puts File.expand_path(File.dirname(__FILE__)) + "/" + path
end
